#########################################
#                                       #
# Instalacion y configuración Server IPA#
#                                       #
#########################################

- name: Instalacion de Servidor IPA
  hosts: Masters
  gather_facts: True
  vars_files:
     - ../var/main.yml
# vars_prompt:
#     - name: "real_password"
#       prompt: "Enter admin password"
#       private: yes
#     - name: "domain_password"
#       prompt: "Enter manager password"
#       private: yes
#  remote_user: root
  tasks:       
     - name: Instalando Paquetes necesarios de Servidor IPA.
       yum: name={{ item }} state=present
       with_items:
               - ipa-server
               - bind-dyndb-ldap
               - ipa-server-dns
             
     - name: Configurando IPA Server.
       command: "ipa-server-install --ip-address={{ ansible_default_ipv4.address }} -r {{ ipaserver_realm }} -n {{ ipaserver_domain }} -p {{ ipaserver_dir_admin_password }} -a {{ ipaserver_admin_password }} --allow-zone-overlap --no-host-dns --mkhomedir --setup-dns --auto-forwarders --hostname={{ hostname_full.name }} --reverse-zone=0.168.192.in-addr.arpa. --subject={{ ipaserver_subject }} -U"
       
     - name: Habilitando puertos en Firewall
       firewalld: port={{ item }} permanent=true state=enabled
       with_items:
         - 80/tcp
         - 443/tcp
         - 389/tcp
         - 636/tcp
         - 88/tcp
         - 464/tcp
         - 88/udp
         - 464/udp
         - 53/tcp
         - 53/udp
         - 123/udp

     - name: Reiniciando servicio  firewall
       command: firewall-cmd --reload
       
     - name: Reiniciando nodo
       shell: sleep 2 && shutdown -r now "Ansible reboot"
       async: 1
       poll: 0
       ignore_errors: true
       
     - name: Esperando conexión con servidor.
       local_action: wait_for
       args:
         host: "{{ inventory_hostname }}"
         port: 22
         state: started
         delay: 30
         timeout: 60
